name: CI/CD Docker Hub Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASS }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/devops-app:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/devops-app:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USER }}/devops-app:latest
            docker stop devops-app || true
            docker rm devops-app || true
            docker run -d -p 80:5000 --name devops-app ${{ secrets.DOCKER_USER }}/devops-app:latest
